from pathlib import Path
from html import escape
import json, shutil
ROOT=Path(__file__).resolve().parent.parent
OUT=ROOT/'docs'; OUT.mkdir(exist_ok=True)
BASE='https://ai66man.github.io/chatgpt-plus-sub/'
SHOP='https://fe.dtyuedan.cn/shop/panghu'
CONTACT='https://www.goplus.pro/#wechat'
products=[
 dict(slug='chatgpt-plus',name='ChatGPT Plus',brand='gpt',group='chatgpt',tag='日常工作，轻松加速',price='165',unit='起',mode='自助充值',audience='写作者、学生、办公与轻量编程用户',desc='从写作、资料整理到编程辅助，让 AI 进入你的日常工作。',features=['写作润色与学习辅导','文件分析与联网搜索','Codex 编程辅助','开通前确认账号与订阅状态']),
 dict(slug='chatgpt-pro-5x',name='ChatGPT Pro 5X',brand='gpt',group='chatgpt',tag='更高强度的工作伙伴',price='790',unit='/月',mode='人工咨询',audience='开发者、研究者、高频办公用户',desc='当日常套餐的用量开始限制工作节奏，可以了解更高档位。',features=['适合较高频率的编程任务','研究与复杂文档处理','按实际使用强度选档','客服确认套餐与交付方式']),
 dict(slug='chatgpt-pro-20x',name='ChatGPT Pro 20X',brand='gpt',group='chatgpt',tag='为持续高频使用准备',price='1480',unit='/月',mode='人工咨询',audience='高频开发、科研与复杂任务用户',desc='面向持续、高强度的 AI 工作流，先确认额度需求再选择。',features=['持续编程与研究工作流','复杂任务与长文档处理','升级前确认当前订阅','人工跟进开通与售后']),
 dict(slug='claude-pro',name='Claude Pro',brand='claude',group='claude',tag='长文档与写作好搭档',price='185',unit='/月',mode='自助充值',audience='内容创作者、研究人员、产品经理',desc='从文章打磨到资料分析，为需要细致表达的工作提供帮助。',features=['长文档阅读与内容整理','写作、分析与代码辅助','适合 Claude Code 入门','购买前确认账号可用状态']),
 dict(slug='claude-max-5x',name='Claude Max 5X',brand='claude',group='claude',tag='为重度 Claude Code 用户',price='900',unit='/月',mode='人工咨询',audience='高频编码、写作与研究用户',desc='适合经常触及 Pro 用量限制、需要更充裕工作空间的用户。',features=['更高强度的 Claude 工作流','长时间编码与分析','先确认用量与重置规则','人工确认后安排交付']),
 dict(slug='claude-max-20x',name='Claude Max 20X',brand='claude',group='claude',tag='持续使用，从容推进',price='1700',unit='/月',mode='人工咨询',audience='全天高频使用 Claude 的专业用户',desc='面向高强度使用场景，按真实需求评估高档位是否值得。',features=['高频 Claude Code 使用','持续研究与复杂项目','根据实际限制选择套餐','人工沟通开通与售后']),
 dict(slug='grok-super',name='Grok Super',brand='grok',group='grok',tag='关注正在发生的事',price='230',unit='/月',mode='自助充值',audience='X 用户、热点追踪与信息研究者',desc='适合关注实时讨论、海外资讯，以及 X 生态内容的用户。',features=['热点话题与信息探索','对话、创作与内容整理','适合 X 生态用户','下单前确认账号和权益'])]
faqs=[('这里是 OpenAI 官方网站吗？','不是。AI Plus 是独立的 AI 订阅信息与购买导航站，与 OpenAI、Anthropic、xAI 无隶属关系。购买入口指向第三方服务商，订阅权益以相应产品官方页面为准。'),('可以用微信或支付宝购买吗？','参考服务商提供微信、支付宝购买渠道。本页的购买按钮会前往小店，具体付款方式、库存与成交价格以下单页面为准。'),('ChatGPT Plus、Pro 和 Codex 怎么选？','日常写作、学习和轻量编程可以先了解 Plus；高频编程与研究再评估 Pro。Codex 的访问方式和可用额度取决于官方当前套餐规则，请在购买前确认，避免把网页套餐和 API 用量混为一谈。'),('Claude Pro 和 Max 怎么选？','先根据使用频率评估 Pro；如果持续触及用量限制，再比较 Max 档位。实际可用量会受模型、任务长度和官方规则影响，并不代表无限使用。'),('网站上的价格就是最终价格吗？','这里展示的是 2026 年 9 月 13 日参考服务商的页面报价，并非官方定价或锁价承诺。套餐名称、价格、库存和实际权益，请在付款前向服务商确认。'),('需要在这个网站提交密码或账号信息吗？','不需要。本网站不接收密码、验证码、会话令牌或充值信息。会话令牌同样可能具有账号访问权限，请勿把它当作普通账号编号随意分享。具体交付方式请在购买前与服务商确认。'),('充值需要多久，售后找谁？','交付时间取决于套餐、库存和账号状态，以服务商确认结果为准。请保存订单号与沟通记录；到账、退款和售后问题由实际收款与交付的服务商处理。'),('现有订阅还没到期，可以续费或升级吗？','请先确认账号当前套餐、剩余时长和订阅渠道，再向服务商核对续费或升级规则。不要默认不同渠道会自动叠加，也不要在未确认时重复下单。')]
guides=[('choose-chatgpt','ChatGPT Plus / Pro 怎么选？','CHATGPT','从日常使用到高频 Codex，按工作强度选择适合自己的套餐。',[('先看你每天用 AI 做什么','如果主要是写邮件、改文章、读资料和轻量编程，可以先了解 Plus。选择套餐的起点应是日常任务，而不是看到更高档位就直接升级。'),('什么时候再考虑 Pro','当编码、研究或复杂文档成为每天的高频任务，并且现有用量经常限制工作，再比较 Pro 档位。记录自己遇到限制的频率，比只看套餐名称更有帮助。'),('Codex 与 API 用量需要分开确认','购买前核对官方当前提供的 Codex 访问方式、限制和额度。不要假定 ChatGPT 订阅自动包含 API 余额，也不要把商家标注的档位理解为所有场景下固定倍数的使用量。'),('付款前确认三件事','确认当前账号是否已有订阅、升级后剩余时长如何处理，以及最终套餐名称与成交价。本站页面报价供比较，下单以服务商实时确认为准。')]),('choose-claude','Claude Pro / Max 怎么选？','CLAUDE','看写作、长文档和 Claude Code 的使用节奏，再决定是否升级。',[('从你的真实使用频率出发','偶尔写作、读报告和辅助编程，先了解 Pro 的具体权益。如果每天长时间使用 Claude Code，再评估更高用量的 Max。'),('先区分偶尔限流与持续不足','偶尔遇到限制，不一定需要升级。观察工作中断是否频繁、是否影响交付，以及更换任务安排能否解决，再决定是否增加预算。'),('不要把更高用量理解为无限','用量会受任务长度、上下文、模型和官方规则影响。购买前查看最新官方说明，向服务商确认所售档位及账户适用条件。'),('保留购买与售后记录','下单前确认当前订阅状态、交付步骤、退款条件。开通后在自己的账号中查看套餐与到期时间，并保留订单记录。')]),('buying-guide','订阅前，先看这份购买指南','GUIDE','支付渠道、账号状态、到账与售后，一次梳理清楚。',[('选择适合自己的购买渠道','具备官方支持的支付条件时，可以查看官方订阅渠道。使用第三方服务时，先了解服务商身份、真实成交价、交付方式与售后约定。'),('确认账号状态与套餐','检查账号能否正常登录，是否有未到期订阅，以及当前订阅来自哪个渠道。先确认自己需要的产品和档位，再进行付款。'),('认真核对交付所需信息','本网站不收集账号凭据。不要在不明页面提交密码、验证码或会话令牌。会话令牌可能提供账号访问权限，即使不提供密码也不代表没有风险。'),('付款后检查到账结果','按实际订单说明完成后，在对应官方产品中检查套餐与有效期。有异常先联系实际服务商并提供订单号，不要连续重复付款。')])]
def link(name):return name+'.html'
def logo(brand):return f'<img src="assets/{brand}.{"png" if brand=="gpt" else "svg"}" width="30" height="30" alt="{brand} 标志">'
def btn(text,url,secondary=False):return f'<a class="button {"secondary" if secondary else ""}" href="{url}">{text}<span aria-hidden="true">↗</span></a>'
def faq(items):return '<div class="faq-list">'+''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in items)+'</div>'
def heading(eyebrow,title,sub):return f'<div class="section-head"><span class="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{sub}</p></div>'
def product_card(p):
 return f'''<article class="product {p['group']}"><div class="card-top"><span class="tag">{p['tag']}</span>{logo(p['brand'])}</div><h3>{p['name']}</h3><div class="price"><small>¥</small>{p['price']}<small>{p['unit']}</small></div><p class="price-note">参考服务商报价 · 以实际下单为准</p><p class="product-desc">{p['desc']}</p><div class="audience"><small>适合人群</small>{p['audience']}</div><ul class="checks">{''.join('<li>'+x+'</li>' for x in p['features'])}</ul><a class="detail-link" href="{link(p['slug'])}">了解套餐详情 <span>→</span></a><div class="card-actions">{btn(p['mode'],SHOP if p['mode']=='自助充值' else CONTACT)}<a href="{CONTACT}">微信咨询</a></div></article>'''
def contact():return f'''<section class="contact-section" id="contact"><div class="container contact-inner"><div><span class="eyebrow">LET’S GET STARTED</span><h2>选好了，就让 AI 开始帮忙。</h2><p>还有疑问？先确认账号、套餐与售后，再决定下单。</p><div class="actions">{btn('前往小店购买',SHOP)}{btn('联系微信客服',CONTACT,True)}</div><small>购买与咨询将前往 GoPlus 服务商页面。</small></div><div class="contact-note"><span class="big-plus">＋</span><strong>你的账号，你的工作流。</strong><p>ChatGPT · Claude · Grok<br>找到适合自己的 AI 订阅。</p></div></div></section>'''
def page(title,desc,body,slug='index'):
 canonical=BASE+(link(slug) if slug!='index' else '')
 nav=[('首页','index.html'),('ChatGPT','index.html#chatgpt'),('Claude','index.html#claude'),('Grok','index.html#grok'),('选购指南','guides.html'),('常见问题','faq.html')]
 return f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{escape(title)} | AI Plus</title><meta name="description" content="{escape(desc)}"><meta name="theme-color" content="#28766d"><link rel="canonical" href="{canonical}"><meta property="og:title" content="{escape(title)}"><meta property="og:description" content="{escape(desc)}"><meta property="og:type" content="website"><meta property="og:url" content="{canonical}"><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/style.css"><script src="assets/app.js" defer></script></head><body><a class="skip-link" href="#main">跳到正文</a><header><div class="container header-inner"><a class="brand" href="index.html" aria-label="AI Plus 首页"><span class="brand-icon">A<span>＋</span></span><span><strong>AI Plus</strong><small>AI 订阅服务</small></span></a><nav id="navigation" aria-label="主导航">{''.join(f'<a href="{u}">{n}</a>' for n,u in nav)}</nav><a class="header-cta" href="{CONTACT}">咨询购买 ↗</a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation" aria-label="展开导航">☰</button></div></header><main id="main">{body}</main><footer><div class="container footer-grid"><div><a class="brand" href="index.html"><span class="brand-icon">A<span>＋</span></span><span><strong>AI Plus</strong><small>把更多时间，留给创造。</small></span></a><p>ChatGPT、Claude、Grok 订阅信息与购买导航。<br>独立第三方信息站，与 OpenAI、Anthropic、xAI 无隶属关系。</p></div><div><strong>探索</strong><a href="index.html#products">全部套餐</a><a href="guides.html">选购指南</a><a href="faq.html">常见问题</a></div><div><strong>关于本站</strong><a href="about.html">关于我们</a><a href="privacy.html">隐私说明</a><a href="terms.html">使用说明</a></div></div><div class="container footer-bottom"><span>© 2026 AI Plus</span><span>价格与套餐信息参考 GoPlus · 更新于 2026-09-13</span></div></footer><div class="mobile-bar">{btn('微信咨询',CONTACT,True)}{btn('选择套餐','index.html#products')}</div></body></html>'''
def write(slug,title,desc,body):
 if slug in ['guides','faq']:
  body=body.replace('<h2>', '<h1>', 1).replace('</h2>', '</h1>', 1)
 (OUT/link(slug)).write_text(page(title,desc,body,slug))
def guidecards():return '<div class="guide-grid">'+''.join(f'<a class="guide-card" href="{link(s)}"><div class="guide-art {s}"><span>{t}</span><b>{"GPT" if t=="CHATGPT" else "Claude" if t=="CLAUDE" else "Before you buy."}</b><i>↗</i></div><div class="guide-text"><h3>{n}</h3><p>{d}</p><span>阅读指南 →</span></div></a>' for s,n,t,d,b in guides)+'</div>'
hero=f'''<section class="hero"><div class="container"><div class="hero-badges"><span>国内支付渠道</span><span>微信 / 支付宝</span><span>开通前可咨询</span></div><h1><span>ChatGPT · Claude · Grok</span><br>AI 订阅，让好工具触手可及</h1><p class="hero-lead">从日常写作，到高频编程。找到适合你的那一档。</p><p class="hero-sub">ChatGPT Plus / Pro、Claude Pro / Max、Grok Super，一站了解，按需选择。</p><div class="actions">{btn('选择 AI 订阅套餐','#products')}{btn('微信咨询',CONTACT,True)}<a class="text-button" href="buying-guide.html">购买前指南 →</a></div><div class="hero-bottom"><span><b>3 大产品</b>覆盖常用 AI 工具</span><span><b>7 款套餐</b>按使用强度选择</span><span><b>自助 / 人工</b>两种购买方式</span></div></div></section>'''
body=hero+'<section class="container section" id="products">'+heading('SUBSCRIPTIONS','热门 AI 订阅套餐','先选工具，再选使用强度。价格为服务商参考报价，实际权益与库存请在购买前确认。')+'<div class="product-tabs">'+''.join(f'<a href="#{g}">{logo(b)}{n}<span>{p}</span></a>' for g,b,n,p in [('chatgpt','gpt','ChatGPT','¥165 起'),('claude','claude','Claude','¥185 /月起'),('grok','grok','Grok','¥230 /月')])+'</div>'
for g,n,d in [('chatgpt','ChatGPT','写作、学习、办公与 Codex 编程辅助。'),('claude','Claude','长文档、细致写作与 Claude Code 工作流。'),('grok','Grok','关注实时话题、海外信息与 X 生态内容。')]:
 body+=f'<div class="product-group" id="{g}"><div class="group-title"><h2>{n} 套餐</h2><p>{d}</p></div><div class="product-grid {"single-product" if g=="grok" else ""}">'+''.join(product_card(p) for p in products if p['group']==g)+('</div></div>')
body+='</section><section class="soft-section"><div class="container section">'+heading('WORKFLOW','开通订阅，步骤很清楚','先确认，再下单；开通后，在自己的账号中核对套餐。')+'<div class="steps">'+''.join(f'<article><span class="step-number">0{i}</span><h3>{n}</h3><p>{d}</p></article>' for i,n,d in [(1,'选好产品与套餐','按使用场景选档，先确认当前账号与订阅状态。'),(2,'咨询或自助下单','基础档前往小店，高配套餐先联系服务商确认。'),(3,'按订单说明开通','核对交付方式和所需信息，保存订单与沟通记录。'),(4,'检查到账与有效期','在官方产品中确认订阅状态，有问题联系服务商。')])+'</div></div></section>'
body+='<section class="container section">'+heading('COMPARE','购买渠道，先了解再选择','不同渠道各有适用条件，支付前看清最终价格和售后约定。')+'''<div class="table-wrap"><table><thead><tr><th scope="col">对比维度</th><th scope="col">第三方服务商</th><th scope="col">官方渠道</th></tr></thead><tbody><tr><th scope="row">购买入口</th><td>小店下单 / 人工咨询</td><td>产品官网或官方 App</td></tr><tr><th scope="row">付款方式</th><td>以小店支持的微信、支付宝等为准</td><td>以官方支持的地区与支付方式为准</td></tr><tr><th scope="row">套餐价格</th><td>商家报价，付款前确认</td><td>官方定价与适用税费</td></tr><tr><th scope="row">交付与售后</th><td>实际服务商负责</td><td>官方支持渠道负责</td></tr><tr><th scope="row">购买前重点</th><td>身份、账号信息要求、退款与交付规则</td><td>地区资格、支付条件与续费规则</td></tr></tbody></table></div></section>'''
body+='<section class="soft-section"><div class="container section">'+heading('GUIDES','开通教程与选购指南','不急着选最贵的，先找到最适合你的。')+guidecards()+'</div></section><section class="container section faq-section">'+heading('FAQ','购买前常见问题','关于套餐、付款、账号与售后，把关键问题放在前面。')+faq(faqs[:6])+'<a class="more-link" href="faq.html">查看全部常见问题 →</a></section>'+contact()
write('index','ChatGPT Plus / Pro、Claude、Grok 订阅充值指南','AI Plus 提供 ChatGPT Plus / Pro、Claude Pro / Max、Grok Super 套餐比较、购买指南与微信支付宝购买入口。',body)
for p in products:
 body=f'<section class="container section"><div class="breadcrumb"><a href="index.html">首页</a> / <a href="index.html#{p["group"]}">订阅套餐</a> / {p["name"]}</div><div class="detail-layout"><div><span class="eyebrow">AI SUBSCRIPTION</span><h1>{p["name"]}<br>订阅与购买指南</h1><p class="intro">{p["desc"]}</p><h2>适合谁？</h2><p>{p["audience"]}。建议从你的实际使用频率出发，购买前确认当前账号、已有订阅和所需权益。</p><h2>购买前确认</h2><ul class="checks">{''.join('<li>'+x+'</li>' for x in p['features'])}</ul><div class="notice">页面价格及档位名称参考 GoPlus（2026-09-13），不代表官方报价。具体功能、使用额度与可用地区以官方最新规则为准，成交价和交付政策以下单时服务商确认为准。</div><h2>怎样开通？</h2><p>先选择套餐，前往小店查看库存与实际价格；人工交付套餐先咨询客服。核对账号状态与交付步骤后再付款，完成后到官方产品中确认订阅状态。</p><a class="detail-link" href="buying-guide.html">阅读完整购买指南 →</a></div>{product_card(p)}</div></section>'+contact()
 write(p['slug'],p['name']+' 充值与订阅指南',p['desc'],body)
for s,n,t,d,sections in guides:
 body=f'<article class="container article section"><div class="breadcrumb"><a href="index.html">首页</a> / <a href="guides.html">选购指南</a></div><span class="eyebrow">{t} GUIDE</span><h1>{n}</h1><p class="intro">{d}</p><p class="article-meta">更新于 2026 年 9 月 13 日 · AI Plus</p>'+''.join(f'<section><h2>{h}</h2><p>{p}</p></section>' for h,p in sections)+f'<div class="notice">延伸阅读：<a href="https://www.goplus.pro/guide">GoPlus 购买说明</a>。产品权益请核对对应官方订阅页面。</div><div class="actions">{btn("查看全部套餐","index.html#products")}</div></article>'
 write(s,n,d,body)
write('guides','AI 订阅选购指南','了解 ChatGPT、Claude 套餐选择和购买流程。','<section class="container section">'+heading('GUIDES','少一点纠结，多一点了解','从使用场景出发，找到适合自己的 AI 订阅。')+guidecards()+'</section>'+contact())
write('faq','AI 订阅常见问题','AI 订阅购买、账号、充值与售后常见问题。','<section class="container section faq-section">'+heading('HELP CENTER','你想知道的，都在这里','付款之前，先把套餐、交付和售后问清楚。')+faq(faqs)+'</section>'+contact())
for slug,title,sections in [
 ('about','关于 AI Plus',[('让选择更清楚','AI Plus 整理 ChatGPT、Claude、Grok 的订阅参考信息，帮助读者比较套餐、了解购买步骤。本站为独立第三方信息与购买导航站，并非上述产品的官方站点。'),('内容与购买入口','套餐报价和服务入口参考 GoPlus，页面标注了信息整理日期。购买和咨询会跳转至外部服务商，实际交易、交付和售后由服务商负责。'),('品牌说明','ChatGPT、Claude、Grok 及相关标志归各自权利人所有，仅用于产品识别。')]),
 ('privacy','隐私说明',[('本站收集哪些信息','本站为静态信息页面，不提供账号登录，不设置支付表单，不主动收集密码、验证码、会话令牌或支付资料，也未接入第三方行为统计。'),('托管与外部链接','网站由 GitHub Pages 托管，托管服务可能按其隐私政策记录请求信息。点击购买或咨询后，会进入第三方网站，并适用对方的隐私政策。'),('账号信息提醒','请勿通过公开渠道或不明页面发送账号凭据。提交交付所需信息前，应明确了解接收方身份、信息用途和访问权限。')]),
 ('terms','网站使用说明',[('信息用途','本站内容为产品比较和购买参考，不构成官方承诺。价格、名称、功能、额度、地区与库存可能变化，请在下单前确认最新信息。'),('第三方交易','本站不直接收款或交付订阅。通过外部链接产生的交易，请与实际服务商确认订单、退款、售后和账号适用条件。'),('使用产品','请遵循对应产品的使用条款与账号安全要求。第三方服务并不能免除官方规则，也不能保证不发生账号或订阅异常。')])]:
 write(slug,title,title+'与网站相关说明。','<article class="container article section"><h1>'+title+'</h1>'+''.join('<section><h2>'+h+'</h2><p>'+p+'</p></section>' for h,p in sections)+'</article>')
write('404','页面未找到','返回 AI Plus 首页查找套餐与指南。','<section class="container section empty"><span class="eyebrow">404</span><h1>这个页面暂时找不到了</h1><p>你可以回到首页继续查看套餐与指南。</p>'+btn('返回首页',BASE)+'</section>')
# The error page can be served for arbitrary nested URLs.
f=OUT/'404.html';s=f.read_text();s=s.replace('href="assets/','href="'+BASE+'assets/').replace('src="assets/','src="'+BASE+'assets/');s=s.replace('<head>','<head><base href="'+BASE+'"><meta name="robots" content="noindex">');s=s.replace('<link rel="canonical" href="'+BASE+'404.html">','');f.write_text(s)
shutil.copytree(ROOT/'assets',OUT/'assets',dirs_exist_ok=True)
(OUT/'.nojekyll').touch()
urls=[BASE]+[BASE+p.name for p in sorted(OUT.glob('*.html')) if p.stem not in ['index','404']]
(OUT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+u+'</loc></url>' for u in urls)+'</urlset>')
print(f'Built {len(urls)} pages + 404')
